version: '3'

services:
  db:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - 3306:3306

  web:
    build: .
    command: bee run --downdoc=true --gendoc=true
    volumes:
      - .:/go/src/basic_blog_go
    working_dir: /go/src/basic_blog_go
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db:3306
      RAPIDAPI_KEY: aa27c56a6dmshbb5af18700bc7fep138e31jsnfd37b629d250
      API_SECRET: bc2153bc4ea0bd9d2cf14f337cf20a257536b24a23dcc40d429e5fc62d06e0b6
      TWITTER_API_KEY: u3GQ06VKyYvYrnGsqXavBe3xt
      TWITTER_API_SECRET: qZJvphGzQudJAsIiRPY3U3WW7bLHWvHGqdDoTRjFlu81JBxA8c
      TWITTER_ACCESS_TOKEN: 98467110-Vh6Qih17uT7aqKekXul6ZuhVctQa3jgn8eWwWOX0L
      TWITTER_ACCESS_TOKEN_SECRET: oJyRMcI5NubNJVQHzuqPT5fha5QPwvZYOJDxl1CItg5JX

    depends_on:
      - db
